name: Build Backend Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Check Containerfile
        run: |
          ls -la
          test -f Containerfile

      - name: Login to Forgejo Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
            docker login main-pc-1.taildccbd1.ts.net:9001 \
            --username "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin

      - name: Build image
        run: |
          docker build \
            -f Containerfile \
            -t main-pc-1.taildccbd1.ts.net:9001/lewin/ppklj-backend:dev \
            .

      - name: Push image
        run: |
          docker push \
            main-pc-1.taildccbd1.ts.net:9001/lewin/ppklj-backend:dev
